App:
  Debug: false
  Name: ApiCat
  AppUrl: http://localhost:8000
  AppServerBind: 0.0.0.0:8000
  MockUrl: http://localhost:8001
  MockServerBind: 0.0.0.0:8001
Database:
  Host: 127.0.0.1:3306
  Username: root
  Password: apicat123456
  Database: apicat
Cache:
  Host: 127.0.0.1:6379
  Password: apicat123456
  Database: 0