version: '3.8'

services:
  apicat:
    depends_on:
      - apicat_db
      - apicat_redis
    image: natuo/apicat:latest
    environment:
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - APP_SERVER_BIND=0.0.0.0:8000
      - MOCK_URL=http://localhost:8001
      - MOCK_SERVER_BIND=0.0.0.0:8001
      - DB_HOST=apicat_db:3306
      - DB_USERNAME=root
      - DB_PASSWORD=apicat123456
      - DB_DATABASE=apicat
      - REDIS_HOST=apicat_redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - STORAGE_DRIVER=disk
      - LOCAL_DISK_PATH=./uploads
    networks:
      - apicat_network
    volumes:
      - apicat_uploads:/app/uploads
    ports:
      - "8000:8000"
      - "8001:8001"
    entrypoint:
      - /bin/bash
      - /app/wait-for-it.sh
      - apicat_db:3306
      - -s
      - -t
      - "60"
      - --
      - /app/apicat-server

  apicat_db:
    image: mysql:8.2
    environment:
      - MYSQL_ROOT_PASSWORD=apicat123456
      - MYSQL_DATABASE=apicat
    networks:
      - apicat_network
    volumes:
      - apicat_db_data:/var/lib/mysql

  apicat_redis:
    image: redis:6-alpine
    networks:
      - apicat_network

networks:
  apicat_network:
    driver: bridge

volumes:
  apicat_uploads:
  apicat_db_data: