version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7.18
    container_name: mysql
    volumes:
      - ./deploy/mysql/mydir:/mydir
      - ./deploy/mysql/datadir:/var/lib/mysql
      - ./deploy/mysql/conf/my.cnf:/etc/my.cnf
      - ./deploy/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=apicat"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306

  apicat-server:
    restart: always
    image: apicat:latest
    ports:
      - 8000:8000
