version: '3.8'

services:
  apicat:
    depends_on:
      - apicat_db
      - apicat_redis
    image: natuo/apicat:latest
    environment:
      - APICAT_DEBUG=false
      - APICAT_APP_SERVER_BIND=0.0.0.0:8000
      - APICAT_MOCK_SERVER_BIND=0.0.0.0:8001
      - APICAT_DB_HOST=apicat_db:3306
      - APICAT_DB_USERNAME=root
      - APICAT_DB_PASSWORD=apicat123456
      - APICAT_DB_DATABASE=apicat
      - APICAT_CACHE_HOST=apicat_redis:6379
      - APICAT_CACHE_PASSWORD=
      - APICAT_CACHE_DB=0
    networks:
      - apicat_network
    volumes:
      - apicat_uploads:/app/uploads
    ports:
      - "8000:8000"
      - "8001:8001"
    entrypoint:
      - /bin/bash
      - /app/wait-for-it.sh
      - apicat_db:3306
      - -s
      - -t
      - "60"
      - --
      - /app/apicat-server

  apicat_db:
    image: mysql:8.2
    environment:
      - MYSQL_ROOT_PASSWORD=apicat123456
      - MYSQL_DATABASE=apicat
    networks:
      - apicat_network
    volumes:
      - apicat_db_data:/var/lib/mysql

  apicat_redis:
    image: redis:6-alpine
    networks:
      - apicat_network

networks:
  apicat_network:
    driver: bridge

volumes:
  apicat_uploads:
  apicat_db_data: