application:
  name: ApiCat
  host: 0.0.0.0
  port: 8000
log:
  path: logs/
  level: debug
database:
  driver: mysql
  # if driver is sqlite path will be using.
  path: data/
  # if you use docker-compose host is mysql.
  host: mysql
  port: 3306
  user: root
  password: 123456
  dbname: apicat
  charset: utf8mb4
openai:
  key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx